image:
  repository:
  tag:

command: []
args: []

envs: []
port:

serviceAccount:
  annotations: {}
  labels: {}
  name:

resourceRequests: {}
resourceLimits: {}

replicas:
  autoscalingEnabled: false
  replicaCount:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: true
  className:
  host:
  path:

commonLabels: {}

pod:
  annotations: {}
  labels: {}
